import {useEffect,useState} from 'react';
import {ArrowRight, Camera, ImagePlus, LockKeyhole, Upload} from 'lucide-react';
import {api,json} from './api';
import {Modal} from './components';
import type {Observation,Sample,Settings,User} from './types';

export function AuthScreen({initialized,onLogin}:{initialized:boolean;onLogin:(user:User)=>void}){
  const [busy,setBusy]=useState(false),[error,setError]=useState('');
  async function submit(event:React.FormEvent<HTMLFormElement>){
    event.preventDefault();setBusy(true);setError('');
    const values=Object.fromEntries(new FormData(event.currentTarget));
    try{onLogin(await api<User>(initialized?'/auth/login':'/auth/setup',json('POST',values)));}catch(e){setError((e as Error).message);}finally{setBusy(false);}
  }
  return <div className="auth-layout"><div className="auth-context"><div className="auth-brand"><Camera size={25}/><span>Déchets urbains</span></div><div><p className="eyebrow">Goma</p><h1>Segmentation des déchets urbains</h1><p>Un registre photographique pour la segmentation et la localisation des déchets urbains.</p><div className="auth-workflow"><span>Photographie</span><ArrowRight size={16}/><span>Segmentation</span><ArrowRight size={16}/><span>Vérification</span></div></div></div><main className="auth-main"><form className="auth-form" onSubmit={submit}><LockKeyhole size={25}/><h2>{initialized?'Connexion':'Configurer le projet'}</h2><p>{initialized?'Connectez-vous avec votre compte.':'Créez votre compte administrateur pour commencer.'}</p>{error&&<p className="form-error" role="alert">{error}</p>}{!initialized&&<label>Votre nom<input name="name" required minLength={2} maxLength={120} autoComplete="name" autoFocus/></label>}<label>Identifiant<input name="login" required minLength={3} maxLength={120} autoComplete="username" autoFocus={initialized}/></label><label>Mot de passe<input name="password" type="password" required minLength={10} maxLength={200} autoComplete={initialized?'current-password':'new-password'}/></label>{!initialized&&<p className="field-help">Au moins 10 caractères. Conservez cet identifiant et ce mot de passe.</p>}<button type="submit" className="btn primary" disabled={busy}>{busy?'Veuillez patienter…':initialized?'Se connecter':'Créer le compte'}</button></form></main></div>;
}

export function UploadModal({onClose,onCreated,settings,neighborhoods}:{onClose:()=>void;onCreated:(row:Observation,analyze:boolean)=>Promise<void>;settings:Settings;neighborhoods:string[]}){
  const [file,setFile]=useState<File|null>(null),[preview,setPreview]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[samples,setSamples]=useState<Sample[]>([]),[showSamples,setShowSamples]=useState(false);
  const [title,setTitle]=useState(''),[notes,setNotes]=useState('');
  useEffect(()=>{if(!file){setPreview('');return;}const url=URL.createObjectURL(file);setPreview(url);return()=>URL.revokeObjectURL(url);},[file]);
  async function examples(){try{setSamples(await api<Sample[]>('/samples'));setShowSamples(true);}catch(e){setError((e as Error).message);}}
  async function chooseSample(sample:Sample){
    try{const response=await fetch('/api/samples/'+sample.id);if(!response.ok)throw new Error('Image exemple indisponible.');setFile(new File([await response.blob()],sample.id+'.jpg',{type:'image/jpeg'}));setTitle(sample.title);setNotes(sample.description+' Source : '+sample.source);setShowSamples(false);}catch(e){setError((e as Error).message);}
  }
  async function submit(event:React.FormEvent<HTMLFormElement>){
    event.preventDefault();setError('');if(!file){setError('Choisissez une photographie.');return;}if(file.size>15*1024*1024){setError('Le fichier dépasse 15 Mo.');return;}
    const values=new FormData(event.currentTarget);const auto=values.get('analyze')==='on';values.delete('analyze');values.set('image',file);for(const field of ['latitude','longitude','captured_at'])if(!values.get(field))values.delete(field);
    setBusy(true);
    try{const row=await api<Observation>('/observations',{method:'POST',body:values});await onCreated(row,auto);onClose();}catch(e){setError((e as Error).message);}finally{setBusy(false);}
  }
  return <Modal title="Ajouter une observation" onClose={()=>{if(!busy)onClose();}} wide><form className="modal-body" onSubmit={submit}>{error&&<p className="form-error" role="alert">{error}</p>}<div className="upload-layout"><div><label className={'upload-drop '+(file?'has-file':'')}><input type="file" name="file-picker" accept="image/jpeg,image/png,image/webp" onChange={e=>setFile(e.target.files?.[0]||null)}/>{preview?<img src={preview} alt="Aperçu de la photographie à importer"/>:<><Upload size={28}/><strong>Choisir une photographie</strong><span>JPEG, PNG ou WebP · 15 Mo maximum</span></>}</label>{file&&<p className="field-help">{file.name} · {(file.size/1024/1024).toFixed(1)} Mo</p>}<button className="text-button sample-button" type="button" onClick={examples}><ImagePlus size={16}/>Utiliser une image exemple</button>{showSamples&&<div className="sample-list"><p className="field-help">Exemples externes pour tester le modèle. Leur lieu n’est pas renseigné.</p>{samples.map(sample=><button type="button" key={sample.id} onClick={()=>chooseSample(sample)}><img src={'/api/samples/'+sample.id} alt=""/><span>{sample.title}</span></button>)}</div>}</div><div><label>Titre<input name="title" required maxLength={120} value={title} onChange={e=>setTitle(e.target.value)} placeholder="Ex. Dépôt près du marché"/></label><div className="field-grid"><label>Quartier<input name="neighborhood" maxLength={120} list="neighborhood-list"/><datalist id="neighborhood-list">{neighborhoods.map(x=><option key={x} value={x}/>)}</datalist></label><label>Date de capture<input type="date" name="captured_at"/></label></div><label>Lieu ou repère<input name="location" maxLength={160} placeholder="Adresse, rue ou point de repère"/></label><fieldset><legend>Coordonnées géographiques <span>facultatives</span></legend><div className="field-grid"><label>Latitude<input name="latitude" type="number" step="any" min={-90} max={90}/></label><label>Longitude<input name="longitude" type="number" step="any" min={-180} max={180}/></label></div><p className="field-help">Les coordonnées GPS de la photo sont utilisées si elles sont présentes et qu’aucune coordonnée n’est saisie.</p></fieldset><label>Notes<textarea name="notes" rows={2} maxLength={4000} value={notes} onChange={e=>setNotes(e.target.value)}/></label><label className="checkbox-label"><input name="analyze" type="checkbox" defaultChecked/>Lancer l’analyse après l’import</label><p className="field-help">Seuil de confiance : {settings.default_confidence}. Le résultat pourra ensuite être vérifié.</p></div></div><div className="modal-actions"><button type="button" className="btn" disabled={busy} onClick={onClose}>Annuler</button><button type="submit" className="btn primary" disabled={busy}>{busy?'Enregistrement…':'Enregistrer l’observation'}</button></div></form></Modal>;
}

export function SettingsPage({settings,user,onSaved,notify}:{settings:Settings;user:User;onSaved:()=>Promise<void>;notify:(message:string)=>void}){
  const [people,setPeople]=useState<User[]>([]),[busy,setBusy]=useState(false);
  useEffect(()=>{if(user.role==='admin')api<User[]>('/users').then(setPeople).catch(e=>notify(e.message));},[user.role]);
  async function save(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const data=Object.fromEntries(new FormData(event.currentTarget));setBusy(true);try{await api('/settings',json('PUT',{...data,default_confidence:Number(data.default_confidence)}));await onSaved();notify('Paramètres enregistrés.');}catch(e){notify((e as Error).message);}finally{setBusy(false);}}
  async function password(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget;setBusy(true);try{await api('/auth/password',json('PUT',Object.fromEntries(new FormData(form))));form.reset();notify('Mot de passe modifié.');}catch(e){notify((e as Error).message);}finally{setBusy(false);}}
  async function addUser(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget;setBusy(true);try{await api('/users',json('POST',Object.fromEntries(new FormData(form))));form.reset();setPeople(await api<User[]>('/users'));notify('Compte créé.');}catch(e){notify((e as Error).message);}finally{setBusy(false);}}
  return <div className="settings-grid">{user.role==='admin'&&<section className="panel"><div className="panel-heading"><h2>Projet</h2></div><form className="panel-body" onSubmit={save} key={JSON.stringify(settings)}><label>Nom du projet<input name="project_name" required minLength={2} maxLength={120} defaultValue={settings.project_name}/></label><label>Ville<input name="city" required minLength={2} maxLength={120} defaultValue={settings.city}/></label><label>Seuil de confiance par défaut<input name="default_confidence" type="number" step={.05} min={.05} max={.95} required defaultValue={settings.default_confidence}/></label><p className="field-help">Un seuil plus faible peut augmenter les détections et les faux positifs. Ce score ne mesure pas la précision globale du modèle.</p><button className="btn primary" disabled={busy}>Enregistrer</button></form></section>}<section className="panel"><div className="panel-heading"><h2>Mon compte</h2></div><form className="panel-body" onSubmit={password}><p className="account-name">{user.name}<small>{user.login} · {user.role==='admin'?'Administrateur':user.role==='agent'?'Agent':'Vérificateur'}</small></p><label>Mot de passe actuel<input name="current_password" type="password" autoComplete="current-password" required maxLength={200}/></label><label>Nouveau mot de passe<input name="new_password" type="password" autoComplete="new-password" minLength={10} maxLength={200} required/></label><button className="btn" disabled={busy}>Modifier le mot de passe</button></form></section>{user.role==='admin'&&<section className="panel users-panel"><div className="panel-heading"><h2>Comptes et accès</h2></div><div className="panel-body"><div className="table-scroll"><table><thead><tr><th>Nom</th><th>Identifiant</th><th>Rôle</th></tr></thead><tbody>{people.map(x=><tr key={x.id}><td>{x.name}</td><td>{x.login}</td><td>{x.role==='admin'?'Administrateur':x.role==='agent'?'Agent':'Vérificateur'}</td></tr>)}</tbody></table></div><p className="field-help roles-help">Agent : import et analyse. Vérificateur : examen des résultats. Administrateur : ensemble des fonctions.</p><form className="user-form" onSubmit={addUser}><h3>Ajouter un compte</h3><div className="field-grid"><label>Nom<input name="name" required minLength={2} maxLength={120}/></label><label>Identifiant<input name="login" required minLength={3} maxLength={120} autoComplete="off"/></label><label>Mot de passe initial<input name="password" type="password" required minLength={10} maxLength={200} autoComplete="new-password"/></label><label>Rôle<select name="role"><option value="agent">Agent</option><option value="reviewer">Vérificateur</option><option value="admin">Administrateur</option></select></label></div><button className="btn" disabled={busy}>Créer le compte</button></form></div></section>}</div>;
}
